index-url = "https://pypi.org/simple"
extra-index-url = [
    "https://mirrors.aliyun.com/pypi/simple",
    "https://pypi.tuna.tsinghua.edu.cn/simple",
    "https://pypi.mirrors.ustc.edu.cn/simple/",
    "https://mirror.sjtu.edu.cn/pypi/web/simple/",
]
