[[index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
[[index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true
[[index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
[[index]]
name = "ustc"
url = "https://pypi.mirrors.ustc.edu.cn/simple/"
[[index]]
name = "sjtu"
url = "https://mirror.sjtu.edu.cn/pypi/web/simple/"
